// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using WebTests.Data;

#nullable disable

namespace WebTests.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            // MANY-TO-MANY TABLE TestTestTypes
            modelBuilder.Entity("TestTestTypes", b =>
            {
                b.Property<int>("TestsId").HasColumnType("int");
                b.Property<int>("TypesId").HasColumnType("int");

                b.HasKey("TestsId", "TypesId");
                b.HasIndex("TypesId");

                b.ToTable("TestTestTypes");
            });

            // IdentityRole
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
            {
                b.Property<string>("Id").HasColumnType("nvarchar(450)");
                b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("nvarchar(max)");
                b.Property<string>("Name").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("NormalizedName").HasMaxLength(256).HasColumnType("nvarchar(256)");

                b.HasKey("Id");

                b.HasIndex("NormalizedName")
                    .IsUnique()
                    .HasDatabaseName("RoleNameIndex")
                    .HasFilter("[NormalizedName] IS NOT NULL");

                b.ToTable("AspNetRoles", (string)null);
            });

            // IdentityRoleClaim
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<string>("ClaimType").HasColumnType("nvarchar(max)");
                b.Property<string>("ClaimValue").HasColumnType("nvarchar(max)");
                b.Property<string>("RoleId").IsRequired().HasColumnType("nvarchar(450)");

                b.HasKey("Id");
                b.HasIndex("RoleId");

                b.ToTable("AspNetRoleClaims", (string)null);
            });

            // IdentityUser
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
            {
                b.Property<string>("Id").HasColumnType("nvarchar(450)");
                b.Property<int>("AccessFailedCount").HasColumnType("int");
                b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("nvarchar(max)");
                b.Property<string>("Email").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<bool>("EmailConfirmed").HasColumnType("bit");
                b.Property<bool>("LockoutEnabled").HasColumnType("bit");
                b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("datetimeoffset");
                b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("PasswordHash").HasColumnType("nvarchar(max)");
                b.Property<string>("PhoneNumber").HasColumnType("nvarchar(max)");
                b.Property<bool>("PhoneNumberConfirmed").HasColumnType("bit");
                b.Property<string>("SecurityStamp").HasColumnType("nvarchar(max)");
                b.Property<bool>("TwoFactorEnabled").HasColumnType("bit");
                b.Property<string>("UserName").HasMaxLength(256).HasColumnType("nvarchar(256)");

                b.HasKey("Id");

                b.HasIndex("NormalizedEmail").HasDatabaseName("EmailIndex");
                b.HasIndex("NormalizedUserName")
                    .IsUnique()
                    .HasDatabaseName("UserNameIndex")
                    .HasFilter("[NormalizedUserName] IS NOT NULL");

                b.ToTable("AspNetUsers", (string)null);
            });

            // IdentityUserClaim
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<string>("ClaimType").HasColumnType("nvarchar(max)");
                b.Property<string>("ClaimValue").HasColumnType("nvarchar(max)");
                b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(450)");

                b.HasKey("Id");
                b.HasIndex("UserId");

                b.ToTable("AspNetUserClaims", (string)null);
            });

            // IdentityUserLogin
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.Property<string>("LoginProvider").HasColumnType("nvarchar(450)");
                b.Property<string>("ProviderKey").HasColumnType("nvarchar(450)");
                b.Property<string>("ProviderDisplayName").HasColumnType("nvarchar(max)");
                b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(450)");

                b.HasKey("LoginProvider", "ProviderKey");
                b.HasIndex("UserId");

                b.ToTable("AspNetUserLogins", (string)null);
            });

            // IdentityUserRole
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.Property<string>("UserId").HasColumnType("nvarchar(450)");
                b.Property<string>("RoleId").HasColumnType("nvarchar(450)");

                b.HasKey("UserId", "RoleId");
                b.HasIndex("RoleId");

                b.ToTable("AspNetUserRoles", (string)null);
            });

            // IdentityUserToken
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.Property<string>("UserId").HasColumnType("nvarchar(450)");
                b.Property<string>("LoginProvider").HasColumnType("nvarchar(450)");
                b.Property<string>("Name").HasColumnType("nvarchar(450)");
                b.Property<string>("Value").HasColumnType("nvarchar(max)");

                b.HasKey("UserId", "LoginProvider", "Name");

                b.ToTable("AspNetUserTokens", (string)null);
            });

            // AnswerOption
            modelBuilder.Entity("WebTests.Models.AnswerOption", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<bool>("IsCorrect").HasColumnType("bit");
                b.Property<int>("QuestionId").HasColumnType("int");
                b.Property<string>("Text").IsRequired().HasColumnType("nvarchar(max)");

                b.HasKey("Id");
                b.HasIndex("QuestionId");

                b.ToTable("AnswerOptions");
            });

            // Question
            modelBuilder.Entity("WebTests.Models.Question", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<int>("TestId").HasColumnType("int");
                b.Property<string>("Text").IsRequired().HasColumnType("nvarchar(max)");

                b.HasKey("Id");
                b.HasIndex("TestId");

                b.ToTable("Questions");
            });

            // Test
            modelBuilder.Entity("WebTests.Models.Test", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<string>("CreatorId").HasColumnType("nvarchar(450)");
                b.Property<bool>("Published").HasColumnType("bit");
                b.Property<string>("Title").IsRequired().HasColumnType("nvarchar(max)");

                b.HasKey("Id");
                b.HasIndex("CreatorId");

                b.ToTable("Tests");
            });

            // TestTypes
            modelBuilder.Entity("WebTests.Models.TestTypes", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<string>("Description").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("TestTypes");
            });

            // RELATIONS -------------------------------------------------------

            // Many-to-Many Test ↔ TestTypes
            modelBuilder.Entity("TestTestTypes", b =>
            {
                b.HasOne("WebTests.Models.Test", null)
                    .WithMany()
                    .HasForeignKey("TestsId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("WebTests.Models.TestTypes", null)
                    .WithMany()
                    .HasForeignKey("TypesId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            // IdentityRoleClaim → Role
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            // IdentityUserClaim → User
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            // IdentityUserLogin → User
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            // IdentityUserRole → Role + User
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            // IdentityUserToken → User
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            // AnswerOption → Question
            modelBuilder.Entity("WebTests.Models.AnswerOption", b =>
            {
                b.HasOne("WebTests.Models.Question", "Question")
                    .WithMany("Options")
                    .HasForeignKey("QuestionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Question");
            });

            // Question → Test
            modelBuilder.Entity("WebTests.Models.Question", b =>
            {
                b.HasOne("WebTests.Models.Test", "Test")
                    .WithMany("Questions")
                    .HasForeignKey("TestId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Test");
            });

            // Test → Creator (IdentityUser)
            modelBuilder.Entity("WebTests.Models.Test", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Creator")
                    .WithMany()
                    .HasForeignKey("CreatorId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Creator");
            });

            // Navigation properties
            modelBuilder.Entity("WebTests.Models.Question", b =>
            {
                b.Navigation("Options");
            });

            modelBuilder.Entity("WebTests.Models.Test", b =>
            {
                b.Navigation("Questions");
            });

#pragma warning restore 612, 618
        }
    }
}
